{
 "title": "dash-forum-api",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values({instance=\"$instance\", application=\"$application\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "NON-HEAP USED",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOAD AVG",
     "type": "timeseries",
     "description": "AVG CPU Usage",
     "gridPos": { "h": 8, "w": 16, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    },
    {
     "title": "HEAP USED",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "API RED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MAX REQUEST DURATION",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "AVAREGE REQUEST DURATION",
     "type": "timeseries",
     "description": "Avg duration of requests",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "REQUEST COUNT",
     "type": "timeseries",
     "description": "Last Minute Request Count",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos\"}[1m]))",
       "legendFormat": "/topicos"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos/{id}\"}[1m]))",
       "legendFormat": "/topicos/{id}"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/auth\"}[1m]))",
       "legendFormat": "/auth"
      }
     ]
    },
    {
     "title": "LATENCY AVERAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "25%"
      }
     ]
    },
    {
     "title": "ERROR 500",
     "type": "stat",
     "description": "Count Error 500",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB TIMEOUT",
     "type": "stat",
     "description": "Database Connection that Handle Timetout",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TOTAL REQUESTS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JDBC POOL",
     "type": "stat",
     "description": "JDBC Connection Pool",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ERROR RATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "500"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "400"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "404"
      }
     ]
    },
    {
     "title": "RESPONSE TIME",
     "type": "timeseries",
     "description": "Endpoints Reponse Time Last Minute",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API BASIC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "API UPTIME",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "USERS LOGGED",
     "type": "stat",
     "description": "Last Minute Users Logged",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CONNECTION STATE",
     "type": "timeseries",
     "description": "Database Connection State",
     "gridPos": { "h": 10, "w": 14, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "START TIME",
     "type": "stat",
     "description": "Start Time API",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AUTH ERROR",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WARN & ERROR LOG",
     "type": "timeseries",
     "description": "Warning and Errors in the last 05 minutes.",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[5m]))",
       "legendFormat": "warn"
      },
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  }
 ]
}